// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoSr2C24V0YLveCy5eAw1AhlJ6BvbVyxQ',
    appId: '1:821410563127:web:0de0fbd2665f06fa0b2bb2',
    messagingSenderId: '821410563127',
    projectId: 'post-wall-talky',
    authDomain: 'post-wall-talky.firebaseapp.com',
    storageBucket: 'post-wall-talky.appspot.com',
    measurementId: 'G-0L5WM2BMQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNcGZ0hE_I4z2zUu_3Yj5ZO0yS4oVv4D4',
    appId: '1:821410563127:android:407c58fa5b335d530b2bb2',
    messagingSenderId: '821410563127',
    projectId: 'post-wall-talky',
    storageBucket: 'post-wall-talky.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQYmdIPJeviCEFCOeeSgSPtegMo4pg4fg',
    appId: '1:821410563127:ios:a90f9f9d9b1fc12a0b2bb2',
    messagingSenderId: '821410563127',
    projectId: 'post-wall-talky',
    storageBucket: 'post-wall-talky.appspot.com',
    iosClientId: '821410563127-bdsbek4shs2f661qutgvtnb36c27lm6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.postWall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQYmdIPJeviCEFCOeeSgSPtegMo4pg4fg',
    appId: '1:821410563127:ios:a90f9f9d9b1fc12a0b2bb2',
    messagingSenderId: '821410563127',
    projectId: 'post-wall-talky',
    storageBucket: 'post-wall-talky.appspot.com',
    iosClientId: '821410563127-bdsbek4shs2f661qutgvtnb36c27lm6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.postWall',
  );
}
